export type LinkCodeStatus = 'active' | 'used' | 'expired' | 'revoked';

/**
 * Who a link code is meant for. Scopes the one-active-code-per-channel
 * supersede policy so a staff-issued code and a guardian's co-parent invite
 * can be active at the same time without clobbering each other.
 * - `staff_issued`: generated by school staff (the admin portal only ever
 *   creates this kind).
 * - `co_parent_invite`: generated by an already-linked guardian from the
 *   parent app to invite a second guardian (e.g. a separated parent).
 */
export type LinkCodeIntent = 'staff_issued' | 'co_parent_invite';

export interface StudentLinkCode {
  id: string;
  code: string;
  schoolId: string;
  studentId: string;
  studentName: string;
  classId: string;
  status: LinkCodeStatus;
  intendedFor: LinkCodeIntent;
  note?: string;
  createdAt: Date;
  expiresAt: Date;
  usedAt?: Date;
  usedBy?: string;
  createdBy: string;
}
