import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

/// One entry in the Lumi app-icon pack.
class LumiAppIcon {
  /// Stable identifier; also the preview asset's basename.
  final String id;

  /// Name shown in the picker.
  final String displayName;

  /// Alternate-icon set name in Assets.xcassets, or null for the primary icon.
  final String? iosIconName;

  const LumiAppIcon({
    required this.id,
    required this.displayName,
    this.iosIconName,
  });

  String get previewAsset => 'assets/app_icons/$id.png';

  bool get isDefault => iosIconName == null;
}

/// The icon pack, in picker display order (default first).
///
/// [LumiAppIcon.iosIconName] values must match the alternate icon sets in
/// ios/Runner/Assets.xcassets and the ASSETCATALOG_COMPILER_ALTERNATE_APPICON_NAMES
/// build setting. Both they and the preview assets are generated by
/// scripts/generate_app_icons.py — keep the three in sync.
const List<LumiAppIcon> kLumiAppIcons = [
  LumiAppIcon(id: 'red_face', displayName: 'Red Face'),
  LumiAppIcon(
      id: 'blue_face', displayName: 'Blue Face', iosIconName: 'AppIconBlueFace'),
  LumiAppIcon(
      id: 'green_face',
      displayName: 'Green Face',
      iosIconName: 'AppIconGreenFace'),
  LumiAppIcon(
      id: 'yellow_face',
      displayName: 'Yellow Face',
      iosIconName: 'AppIconYellowFace'),
  LumiAppIcon(
      id: 'red_lumi', displayName: 'Red Lumi', iosIconName: 'AppIconRedLumi'),
  LumiAppIcon(
      id: 'blue_lumi', displayName: 'Blue Lumi', iosIconName: 'AppIconBlueLumi'),
  LumiAppIcon(
      id: 'light_blue_lumi',
      displayName: 'Light Blue Lumi',
      iosIconName: 'AppIconLightBlueLumi'),
  LumiAppIcon(
      id: 'green_lumi',
      displayName: 'Green Lumi',
      iosIconName: 'AppIconGreenLumi'),
  LumiAppIcon(
      id: 'orange_lumi',
      displayName: 'Orange Lumi',
      iosIconName: 'AppIconOrangeLumi'),
  LumiAppIcon(
      id: 'pink_lumi', displayName: 'Pink Lumi', iosIconName: 'AppIconPinkLumi'),
  LumiAppIcon(
      id: 'purple_lumi',
      displayName: 'Purple Lumi',
      iosIconName: 'AppIconPurpleLumi'),
  LumiAppIcon(
      id: 'yellow_lumi',
      displayName: 'Yellow Lumi',
      iosIconName: 'AppIconYellowLumi'),
];

/// Thin wrapper over the `lumi/app_icon` MethodChannel (AppIconChannel.swift).
///
/// iOS itself persists the applied icon across launches, so there is no local
/// state to store — the current selection is always read back from the system.
class AppIconService {
  static const MethodChannel _channel = MethodChannel('lumi/app_icon');

  /// Cheap synchronous check used to hide entry points on platforms that can
  /// never switch icons. [isSupported] asks iOS for the definitive answer.
  static bool get isSupportedPlatform =>
      !kIsWeb && defaultTargetPlatform == TargetPlatform.iOS;

  Future<bool> isSupported() async {
    if (!isSupportedPlatform) return false;
    return await _channel.invokeMethod<bool>('isSupported') ?? false;
  }

  /// The active icon, resolved against [kLumiAppIcons]; falls back to the
  /// default entry if iOS reports an icon name the catalog no longer contains.
  Future<LumiAppIcon> currentIcon() async {
    final name = await _channel.invokeMethod<String>('getAlternateIconName');
    return kLumiAppIcons.firstWhere(
      (icon) => icon.iosIconName == name,
      orElse: () => kLumiAppIcons.first,
    );
  }

  /// Applies [icon]. iOS shows its own confirmation alert on success; throws
  /// a [PlatformException] on failure (e.g. unknown icon name).
  Future<void> setIcon(LumiAppIcon icon) {
    return _channel.invokeMethod<void>(
      'setAlternateIconName',
      {'iconName': icon.iosIconName},
    );
  }
}
