// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHmA2rTie2aII3J5RhYOQlEYvycDPxPTw',
    appId: '1:3795320704:android:47b629e400e8419c37cb65',
    messagingSenderId: '3795320704',
    projectId: 'lumi-ninc-au',
    storageBucket: 'lumi-ninc-au.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCimCarq1UJwUJNStyaWSCiZcoFyErCgaM',
    appId: '1:3795320704:ios:4067b645d940238137cb65',
    messagingSenderId: '3795320704',
    projectId: 'lumi-ninc-au',
    storageBucket: 'lumi-ninc-au.firebasestorage.app',
    iosBundleId: 'com.lumi.lumiReadingTracker',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkq469oLpYK7mz3SQfZ2-GIM5Oj9ZgN88',
    appId: '1:3795320704:web:729cb32dab543bd637cb65',
    messagingSenderId: '3795320704',
    projectId: 'lumi-ninc-au',
    authDomain: 'lumi-ninc-au.firebaseapp.com',
    storageBucket: 'lumi-ninc-au.firebasestorage.app',
    measurementId: 'G-7NYPR6FEYK',
  );

}